# Generated by Django 3.2.25 on 2026-01-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblSuperAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdminName', models.CharField(max_length=100)),
                ('UserName', models.CharField(max_length=100, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('MobileNumber', models.CharField(max_length=15)),
                ('Password', models.CharField(max_length=255)),
                ('Role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('SUB_ADMIN', 'Sub Admin')], default='SUPER_ADMIN', max_length=20)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
