# Generated by Django 3.2.25 on 2026-01-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Deptname', models.CharField(max_length=100, unique=True)),
                ('Deptcode', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
