# Generated by Django 3.2.25 on 2026-01-29 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblSubAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subadminfirstname', models.CharField(max_length=100)),
                ('Subadminlastname', models.CharField(max_length=100)),
                ('Subadminemail', models.EmailField(max_length=254, unique=True)),
                ('Subadminmobile', models.CharField(max_length=15)),
                ('Subadminpassword', models.CharField(max_length=15)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.department')),
            ],
        ),
    ]
