# Generated by Django 3.2.25 on 2026-01-29 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_tblsubadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('RollNo', models.CharField(max_length=20, unique=True)),
                ('MobileNo', models.CharField(max_length=15)),
                ('CreatePassword', models.CharField(max_length=15)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.department')),
            ],
        ),
    ]
