# Generated by Django 3.2.25 on 2026-01-30 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.department')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.subject')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.tblsubadmin')),
            ],
        ),
    ]
