# Generated by Django 3.2.25 on 2026-02-06 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='webapp.test'),
        ),
    ]
