# Generated by Django 3.2.25 on 2026-02-24 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_question_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.PositiveIntegerField()),
                ('total_marks', models.PositiveIntegerField()),
                ('obtained_marks', models.PositiveIntegerField()),
                ('percentage', models.FloatField()),
                ('status', models.CharField(max_length=10)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.test')),
                ('studentregistration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.studentregistration')),
            ],
        ),
    ]
