# Generated by Django 3.2.25 on 2026-03-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_studentresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblsubadmin',
            name='Subadminpassword',
            field=models.CharField(max_length=255),
        ),
    ]
