# Generated by Django 3.2.25 on 2026-03-04 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_tblsubadmin_subadminpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.tblsubadmin'),
        ),
    ]
